### ISSUE TITLE
Gamemode specific permissions

### ISSUE THREAD

**Issue by urhuckleberry51** [SupremeMortal/EssentialsNK#11]
Permissions like this
Gmc=Essentialsnk.gmc
Gms=essentialsnk.gms
Gmsp=essentialsnk.gmsp Gma=essentialsnk.gma
Gmt=essentialsnk.gmt

**Comment by MrRazamataz** [comment]
Yes please this is very much needed. 
Im trying to set up a group that can use only spectator and survival and not creative. I have set nukkit.command.gamemode.creative to false but it seems that I need to have essentialsnk.gamemode set to true to be able to switch gamemodes. When I have essentialsnk.gamemode on true, the group can use all gamemodes even though nukkit.command.gamemode.creative is false. Do you know how I can solve this?

**Comment by urhuckleberry51** [comment]
i am not sure i now only code pmmp and not nukkit
