### ISSUE TITLE
Warps problem

### ISSUE THREAD

**Issue by Saxavlax001** [SupremeMortal/EssentialsNK#5]
When you set a warp in another world and you reopen the server and the world you have set the warp is unloaded,the plugin doesn't teleports you to the world that the warp is set,it teleports you to the coords of the world you are already there.Sorry if I confused you,but I just want to make this plugin better.

**Comment by SupremeMortal** [comment]
If you mean the world is unloaded, that's an issue with the plugin that manages worlds. Essentials does not manage it.
